version: '3.7'
services:
  postgres-db:
    image: postgres:latest
    restart: always
    container_name: employee-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=employee-db
    ports:
      - "5432:5432"